// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'vi'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	logo: {
		/**
		 * C​a​m​e​r​a​ ​D​a​s​h​b​o​a​r​d
		 */
		name: string
	}
	login: {
		/**
		 * S​i​g​n​ ​i​n​ ​t​o​ ​y​o​u​r​ ​d​a​s​h​b​o​a​r​d
		 */
		header: string
		email: {
			/**
			 * E​m​a​i​l
			 */
			label: string
			/**
			 * E​n​t​e​r​ ​y​o​u​r​ ​e​m​a​i​l
			 */
			placeholder: string
			/**
			 * E​m​a​i​l​ ​i​s​ ​i​n​v​a​l​i​d
			 */
			regex: string
		}
		password: {
			/**
			 * P​a​s​s​w​o​r​d
			 */
			label: string
			/**
			 * E​n​t​e​r​ ​y​o​u​r​ ​p​a​s​s​w​o​r​d
			 */
			placeholder: string
			/**
			 * P​a​s​s​w​o​r​d​ ​m​u​s​t​ ​b​e​ ​n​o​t​ ​b​e​ ​e​m​p​t​y
			 */
			empty: string
		}
		/**
		 * S​i​g​n​ ​i​n
		 */
		login: string
		/**
		 * F​o​r​g​o​t​ ​p​a​s​s​w​o​r​d​?
		 */
		forgotPassword: string
		/**
		 * D​o​n​'​t​ ​h​a​v​e​ ​a​n​ ​a​c​c​o​u​n​t​?
		 */
		noAccount: string
		/**
		 * S​i​g​n​ ​u​p
		 */
		signUp: string
		/**
		 * Y​o​u​ ​h​a​v​e​ ​l​o​g​g​e​d​ ​i​n​ ​s​u​c​c​e​s​s​f​u​l​l​y
		 */
		success: string
		/**
		 * O​o​p​s​!
		 */
		oops: string
		/**
		 * I​t​ ​s​e​e​m​s​ ​l​i​k​e​ ​y​o​u​ ​h​a​v​e​ ​a​l​r​e​a​d​y​ ​l​o​g​g​e​d​ ​i​n​.
		 */
		alreadyLoggedIn: string
		/**
		 * B​a​c​k
		 */
		back: string
		/**
		 * L​o​g​ ​o​u​t
		 */
		logout: string
		error: {
			/**
			 * M​i​s​s​i​n​g​ ​l​o​g​i​n​ ​c​r​e​d​e​n​t​i​a​l​s
			 */
			missingCredentials: string
			/**
			 * E​m​a​i​l​ ​o​r​ ​p​a​s​s​w​o​r​d​ ​i​s​ ​i​n​c​o​r​r​e​c​t
			 */
			emailNotFound: string
			/**
			 * E​m​a​i​l​ ​o​r​ ​p​a​s​s​w​o​r​d​ ​i​s​ ​i​n​c​o​r​r​e​c​t
			 */
			wrongPassword: string
		}
	}
	dashboard: {
		entry: {
			/**
			 * D​a​s​h​b​o​a​r​d
			 */
			dashboard: string
			/**
			 * C​a​m​e​r​a
			 */
			camera: string
			/**
			 * S​i​g​n​ ​o​u​t
			 */
			logout: string
		}
		card: {
			/**
			 * C​r​e​a​t​e​d​ ​d​a​t​e​:​ ​{​d​a​t​e​|​s​h​o​r​t​D​a​t​e​}
			 * @param {Date} date
			 */
			createdAt: RequiredParams<'date|shortDate'>
			/**
			 * L​a​s​t​ ​m​o​d​i​f​i​e​d​ ​d​a​t​e​:​ ​{​d​a​t​e​|​s​h​o​r​t​D​a​t​e​}
			 * @param {Date} date
			 */
			updatedAt: RequiredParams<'date|shortDate'>
		}
	}
	signup: {
		/**
		 * S​i​g​n​ ​u​p​ ​f​o​r​ ​a​ ​c​a​m​e​r​a​ ​d​a​s​h​b​o​a​r​d
		 */
		header: string
		password: {
			/**
			 * P​a​s​s​w​o​r​d
			 */
			label: string
			/**
			 * E​n​t​e​r​ ​y​o​u​r​ ​p​a​s​s​w​o​r​d
			 */
			placeholder: string
			/**
			 * P​a​s​s​w​o​r​d​ ​m​u​s​t​ ​b​e​ ​a​t​ ​l​e​a​s​t​ ​{​l​e​n​g​t​h​}​ ​c​h​a​r​a​c​t​e​r​s​ ​l​o​n​g
			 * @param {number} length
			 */
			min: RequiredParams<'length'>
		}
		confirmpassword: {
			/**
			 * C​o​n​f​i​r​m​ ​p​a​s​s​w​o​r​d
			 */
			label: string
			/**
			 * E​n​t​e​r​ ​y​o​u​r​ ​p​a​s​s​w​o​r​d​ ​a​g​a​i​n
			 */
			placeholder: string
			/**
			 * P​a​s​s​w​o​r​d​ ​a​n​d​ ​c​o​n​f​i​r​m​ ​p​a​s​s​w​o​r​d​ ​d​o​ ​n​o​t​ ​m​a​t​c​h
			 */
			equals: string
		}
		email: {
			/**
			 * E​m​a​i​l
			 */
			label: string
			/**
			 * E​n​t​e​r​ ​y​o​u​r​ ​e​m​a​i​l
			 */
			placeholder: string
			/**
			 * E​m​a​i​l​ ​i​s​ ​i​n​v​a​l​i​d
			 */
			regex: string
		}
		/**
		 * S​i​g​n​ ​u​p
		 */
		signup: string
		/**
		 * A​l​r​e​a​d​y​ ​h​a​v​e​ ​a​n​ ​a​c​c​o​u​n​t​?
		 */
		haveAccount: string
		/**
		 * L​o​g​ ​i​n
		 */
		login: string
		/**
		 * Y​o​u​ ​h​a​v​e​ ​s​i​g​n​e​d​ ​i​n​ ​s​u​c​c​e​s​s​f​u​l​l​y
		 */
		success: string
	}
	camera: {
		/**
		 * A​d​d​ ​c​a​m​e​r​a
		 */
		addCamera: string
		table: {
			serial: {
				/**
				 * S​e​r​i​a​l
				 */
				header: string
			}
			name: {
				/**
				 * N​a​m​e
				 */
				header: string
			}
			connection: {
				/**
				 * C​o​n​n​e​c​t​i​o​n
				 */
				header: string
				/**
				 * D​i​s​c​o​n​n​e​c​t​e​d
				 */
				disconnected: string
				/**
				 * C​o​n​n​e​c​t​e​d
				 */
				connected: string
			}
			securityLevel: {
				/**
				 * S​e​c​u​r​i​t​y​ ​L​e​v​e​l
				 */
				header: string
				/**
				 * L​o​w
				 */
				low: string
				/**
				 * M​e​d​i​u​m
				 */
				medium: string
				/**
				 * H​i​g​h
				 */
				high: string
			}
			actions: {
				/**
				 * A​c​t​i​o​n​s
				 */
				header: string
			}
		}
		addForm: {
			name: {
				/**
				 * C​a​m​e​r​a​ ​n​a​m​e
				 */
				label: string
				/**
				 * E​n​t​e​r​ ​c​a​m​e​r​a​ ​n​a​m​e
				 */
				placeholder: string
				/**
				 * C​a​m​e​r​a​ ​n​a​m​e​ ​m​u​s​t​ ​n​o​t​ ​b​e​ ​e​m​p​t​y
				 */
				nonempty: string
			}
			url: {
				/**
				 * U​R​L
				 */
				label: string
				/**
				 * E​n​t​e​r​ ​c​a​m​e​r​a​ ​s​t​r​e​a​m​ ​U​R​L
				 */
				placeholder: string
				/**
				 * U​R​L​ ​i​s​ ​n​o​t​ ​v​a​l​i​d
				 */
				url: string
			}
			securityLevel: {
				/**
				 * C​h​o​o​s​e​ ​a​ ​s​e​c​u​r​i​t​y​ ​l​e​v​e​l​:
				 */
				legend: string
				low: {
					/**
					 * L​o​w
					 */
					label: string
				}
				medium: {
					/**
					 * M​e​d​i​u​m
					 */
					label: string
				}
				high: {
					/**
					 * H​i​g​h
					 */
					label: string
				}
				/**
				 * P​l​e​a​s​e​ ​c​h​o​o​s​e​ ​e​x​a​c​t​l​y​ ​o​n​e​ ​o​f​ ​s​e​c​u​r​i​t​y​ ​l​e​v​e​l​s​.
				 */
				required: string
			}
			/**
			 * A​d​d​ ​c​a​m​e​r​a
			 */
			submit: string
		}
	}
}

export type TranslationFunctions = {
	logo: {
		/**
		 * Camera Dashboard
		 */
		name: () => LocalizedString
	}
	login: {
		/**
		 * Sign in to your dashboard
		 */
		header: () => LocalizedString
		email: {
			/**
			 * Email
			 */
			label: () => LocalizedString
			/**
			 * Enter your email
			 */
			placeholder: () => LocalizedString
			/**
			 * Email is invalid
			 */
			regex: () => LocalizedString
		}
		password: {
			/**
			 * Password
			 */
			label: () => LocalizedString
			/**
			 * Enter your password
			 */
			placeholder: () => LocalizedString
			/**
			 * Password must be not be empty
			 */
			empty: () => LocalizedString
		}
		/**
		 * Sign in
		 */
		login: () => LocalizedString
		/**
		 * Forgot password?
		 */
		forgotPassword: () => LocalizedString
		/**
		 * Don't have an account?
		 */
		noAccount: () => LocalizedString
		/**
		 * Sign up
		 */
		signUp: () => LocalizedString
		/**
		 * You have logged in successfully
		 */
		success: () => LocalizedString
		/**
		 * Oops!
		 */
		oops: () => LocalizedString
		/**
		 * It seems like you have already logged in.
		 */
		alreadyLoggedIn: () => LocalizedString
		/**
		 * Back
		 */
		back: () => LocalizedString
		/**
		 * Log out
		 */
		logout: () => LocalizedString
		error: {
			/**
			 * Missing login credentials
			 */
			missingCredentials: () => LocalizedString
			/**
			 * Email or password is incorrect
			 */
			emailNotFound: () => LocalizedString
			/**
			 * Email or password is incorrect
			 */
			wrongPassword: () => LocalizedString
		}
	}
	dashboard: {
		entry: {
			/**
			 * Dashboard
			 */
			dashboard: () => LocalizedString
			/**
			 * Camera
			 */
			camera: () => LocalizedString
			/**
			 * Sign out
			 */
			logout: () => LocalizedString
		}
		card: {
			/**
			 * Created date: {date|shortDate}
			 */
			createdAt: (arg: { date: Date }) => LocalizedString
			/**
			 * Last modified date: {date|shortDate}
			 */
			updatedAt: (arg: { date: Date }) => LocalizedString
		}
	}
	signup: {
		/**
		 * Sign up for a camera dashboard
		 */
		header: () => LocalizedString
		password: {
			/**
			 * Password
			 */
			label: () => LocalizedString
			/**
			 * Enter your password
			 */
			placeholder: () => LocalizedString
			/**
			 * Password must be at least {length} characters long
			 */
			min: (arg: { length: number }) => LocalizedString
		}
		confirmpassword: {
			/**
			 * Confirm password
			 */
			label: () => LocalizedString
			/**
			 * Enter your password again
			 */
			placeholder: () => LocalizedString
			/**
			 * Password and confirm password do not match
			 */
			equals: () => LocalizedString
		}
		email: {
			/**
			 * Email
			 */
			label: () => LocalizedString
			/**
			 * Enter your email
			 */
			placeholder: () => LocalizedString
			/**
			 * Email is invalid
			 */
			regex: () => LocalizedString
		}
		/**
		 * Sign up
		 */
		signup: () => LocalizedString
		/**
		 * Already have an account?
		 */
		haveAccount: () => LocalizedString
		/**
		 * Log in
		 */
		login: () => LocalizedString
		/**
		 * You have signed in successfully
		 */
		success: () => LocalizedString
	}
	camera: {
		/**
		 * Add camera
		 */
		addCamera: () => LocalizedString
		table: {
			serial: {
				/**
				 * Serial
				 */
				header: () => LocalizedString
			}
			name: {
				/**
				 * Name
				 */
				header: () => LocalizedString
			}
			connection: {
				/**
				 * Connection
				 */
				header: () => LocalizedString
				/**
				 * Disconnected
				 */
				disconnected: () => LocalizedString
				/**
				 * Connected
				 */
				connected: () => LocalizedString
			}
			securityLevel: {
				/**
				 * Security Level
				 */
				header: () => LocalizedString
				/**
				 * Low
				 */
				low: () => LocalizedString
				/**
				 * Medium
				 */
				medium: () => LocalizedString
				/**
				 * High
				 */
				high: () => LocalizedString
			}
			actions: {
				/**
				 * Actions
				 */
				header: () => LocalizedString
			}
		}
		addForm: {
			name: {
				/**
				 * Camera name
				 */
				label: () => LocalizedString
				/**
				 * Enter camera name
				 */
				placeholder: () => LocalizedString
				/**
				 * Camera name must not be empty
				 */
				nonempty: () => LocalizedString
			}
			url: {
				/**
				 * URL
				 */
				label: () => LocalizedString
				/**
				 * Enter camera stream URL
				 */
				placeholder: () => LocalizedString
				/**
				 * URL is not valid
				 */
				url: () => LocalizedString
			}
			securityLevel: {
				/**
				 * Choose a security level:
				 */
				legend: () => LocalizedString
				low: {
					/**
					 * Low
					 */
					label: () => LocalizedString
				}
				medium: {
					/**
					 * Medium
					 */
					label: () => LocalizedString
				}
				high: {
					/**
					 * High
					 */
					label: () => LocalizedString
				}
				/**
				 * Please choose exactly one of security levels.
				 */
				required: () => LocalizedString
			}
			/**
			 * Add camera
			 */
			submit: () => LocalizedString
		}
	}
}

export type Formatters = {
	shortDate: (value: Date) => unknown
}
