// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'vi'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	logo: {
		/**
		 * C​a​m​e​r​a​ ​D​a​s​h​b​o​a​r​d
		 */
		name: string
	}
	login: {
		/**
		 * S​i​g​n​ ​i​n​ ​t​o​ ​y​o​u​r​ ​d​a​s​h​b​o​a​r​d
		 */
		header: string
		email: {
			/**
			 * E​m​a​i​l
			 */
			label: string
			/**
			 * E​n​t​e​r​ ​y​o​u​r​ ​e​m​a​i​l
			 */
			placeholder: string
			/**
			 * E​m​a​i​l​ ​i​s​ ​i​n​v​a​l​i​d
			 */
			regex: string
		}
		password: {
			/**
			 * P​a​s​s​w​o​r​d
			 */
			label: string
			/**
			 * E​n​t​e​r​ ​y​o​u​r​ ​p​a​s​s​w​o​r​d
			 */
			placeholder: string
			/**
			 * P​a​s​s​w​o​r​d​ ​m​u​s​t​ ​b​e​ ​n​o​t​ ​b​e​ ​e​m​p​t​y
			 */
			empty: string
		}
		/**
		 * S​i​g​n​ ​i​n
		 */
		login: string
		/**
		 * F​o​r​g​o​t​ ​p​a​s​s​w​o​r​d​?
		 */
		forgotPassword: string
		/**
		 * D​o​n​'​t​ ​h​a​v​e​ ​a​n​ ​a​c​c​o​u​n​t​?
		 */
		noAccount: string
		/**
		 * S​i​g​n​ ​u​p
		 */
		signUp: string
		/**
		 * Y​o​u​ ​h​a​v​e​ ​l​o​g​g​e​d​ ​i​n​ ​s​u​c​c​e​s​s​f​u​l​l​y
		 */
		success: string
		/**
		 * O​o​p​s​!
		 */
		oops: string
		/**
		 * I​t​ ​s​e​e​m​s​ ​l​i​k​e​ ​y​o​u​ ​h​a​v​e​ ​a​l​r​e​a​d​y​ ​l​o​g​g​e​d​ ​i​n​.
		 */
		alreadyLoggedIn: string
		/**
		 * B​a​c​k
		 */
		back: string
		/**
		 * L​o​g​ ​o​u​t
		 */
		logout: string
	}
	dashboard: {
		card: {
			/**
			 * C​r​e​a​t​e​d​ ​d​a​t​e​:​ ​{​d​a​t​e​|​s​h​o​r​t​D​a​t​e​}
			 * @param {Date} date
			 */
			createdAt: RequiredParams<'date|shortDate'>
			/**
			 * L​a​s​t​ ​m​o​d​i​f​i​e​d​ ​d​a​t​e​:​ ​{​d​a​t​e​|​s​h​o​r​t​D​a​t​e​}
			 * @param {Date} date
			 */
			updatedAt: RequiredParams<'date|shortDate'>
		}
	signup: {
		/**
		 * S​i​g​n​ ​u​p​ ​f​o​r​ ​a​ ​c​a​m​e​r​a​ ​d​a​s​h​b​o​a​r​d
		 */
		header: string
		password: {
			/**
			 * P​a​s​s​w​o​r​d
			 */
			label: string
			/**
			 * E​n​t​e​r​ ​y​o​u​r​ ​p​a​s​s​w​o​r​d
			 */
			placeholder: string
			/**
			 * P​a​s​s​w​o​r​d​ ​m​u​s​t​ ​b​e​ ​a​t​ ​l​e​a​s​t​ ​{​l​e​n​g​t​h​}​ ​c​h​a​r​a​c​t​e​r​s​ ​l​o​n​g
			 * @param {number} length
			 */
			min: RequiredParams<'length'>
		}
		confirmpassword: {
			/**
			 * C​o​n​f​i​r​m​ ​p​a​s​s​w​o​r​d
			 */
			label: string
			/**
			 * E​n​t​e​r​ ​y​o​u​r​ ​c​o​n​f​i​r​m​p​a​s​s​w​o​r​d
			 */
			placeholder: string
			/**
			 * P​a​s​s​w​o​r​d​ ​a​n​d​ ​c​o​n​f​i​r​m​ ​p​a​s​s​w​o​r​d​ ​d​o​ ​n​o​t​ ​m​a​t​c​h
			 */
			equals: string
		}
		email: {
			/**
			 * E​m​a​i​l
			 */
			label: string
			/**
			 * E​n​t​e​r​ ​y​o​u​r​ ​e​m​a​i​l
			 */
			placeholder: string
			/**
			 * E​m​a​i​l​ ​i​s​ ​i​n​v​a​l​i​d
			 */
			regex: string
		}
		/**
		 * S​i​g​n​ ​u​p
		 */
		signup: string
		/**
		 * A​l​r​e​a​d​y​ ​h​a​v​e​ ​a​n​ ​a​c​c​o​u​n​t​?
		 */
		haveAccount: string
		/**
		 * L​o​g​ ​i​n
		 */
		login: string
		/**
		 * Y​o​u​ ​h​a​v​e​ ​s​i​g​n​e​d​ ​i​n​ ​s​u​c​c​e​s​s​f​u​l​l​y
		 */
		success: string
	}
}

export type TranslationFunctions = {
	logo: {
		/**
		 * Camera Dashboard
		 */
		name: () => LocalizedString
	}
	login: {
		/**
		 * Sign in to your dashboard
		 */
		header: () => LocalizedString
		email: {
			/**
			 * Email
			 */
			label: () => LocalizedString
			/**
			 * Enter your email
			 */
			placeholder: () => LocalizedString
			/**
			 * Email is invalid
			 */
			regex: () => LocalizedString
		}
		password: {
			/**
			 * Password
			 */
			label: () => LocalizedString
			/**
			 * Enter your password
			 */
			placeholder: () => LocalizedString
			/**
			 * Password must be not be empty
			 */
			empty: () => LocalizedString
		}
		/**
		 * Sign in
		 */
		login: () => LocalizedString
		/**
		 * Forgot password?
		 */
		forgotPassword: () => LocalizedString
		/**
		 * Don't have an account?
		 */
		noAccount: () => LocalizedString
		/**
		 * Sign up
		 */
		signUp: () => LocalizedString
		/**
		 * You have logged in successfully
		 */
		success: () => LocalizedString
		/**
		 * Oops!
		 */
		oops: () => LocalizedString
		/**
		 * It seems like you have already logged in.
		 */
		alreadyLoggedIn: () => LocalizedString
		/**
		 * Back
		 */
		back: () => LocalizedString
		/**
		 * Log out
		 */
		logout: () => LocalizedString
	}
	dashboard: {
		card: {
			/**
			 * Created date: {date|shortDate}
			 */
			createdAt: (arg: { date: Date }) => LocalizedString
			/**
			 * Last modified date: {date|shortDate}
			 */
			updatedAt: (arg: { date: Date }) => LocalizedString
		}
	signup: {
		/**
		 * Sign up for a camera dashboard
		 */
		header: () => LocalizedString
		password: {
			/**
			 * Password
			 */
			label: () => LocalizedString
			/**
			 * Enter your password
			 */
			placeholder: () => LocalizedString
			/**
			 * Password must be at least {length} characters long
			 */
			min: (arg: { length: number }) => LocalizedString
		}
		confirmpassword: {
			/**
			 * Confirm password
			 */
			label: () => LocalizedString
			/**
			 * Enter your confirmpassword
			 */
			placeholder: () => LocalizedString
			/**
			 * Password and confirm password do not match
			 */
			equals: () => LocalizedString
		}
		email: {
			/**
			 * Email
			 */
			label: () => LocalizedString
			/**
			 * Enter your email
			 */
			placeholder: () => LocalizedString
			/**
			 * Email is invalid
			 */
			regex: () => LocalizedString
		}
		/**
		 * Sign up
		 */
		signup: () => LocalizedString
		/**
		 * Already have an account?
		 */
		haveAccount: () => LocalizedString
		/**
		 * Log in
		 */
		login: () => LocalizedString
		/**
		 * You have signed in successfully
		 */
		success: () => LocalizedString
	}
}

export type Formatters = {
	shortDate: (value: Date) => unknown
}
